### ISSUE TITLE
Should I root and recompile the kernel on my Android device previously before installing the app?

### ISSUE THREAD

**Issue by QueueRear** [FIGLAB/3DHandPose#1]
Hello, I've read your paper about 3D hand pose estimation and I'm interested in your brilliant work, thus I try to deploy the project. Could you please tell me whether I should recompile the kernel of the device ahead (since it is written in the paper that this project needs a customed touchscreen driver)?
Thx for any help you will offer.

**Comment by sven-mayer** [comment]
Hi @QueueRear,

the provided Android Code only works for a Samsung Galaxy Tab 2 (SM-T813). You can not access the capacitive matrix on all devices; therefore, you need the kernel modification. I can advice to study the [instructions by Huy Viet Le](http://huyle.de/blog/capacitive-images/) where he describes the process for an LG Nexus 5 to create the kernel.

Finally, yes, you need to apply the described kernel modifications before deploying the Android code. This also entails unlocking and rooting your device. 

I hope this helps.
Sven

**Comment by QueueRear** [comment]
@sven-mayer ,

 I'm very grateful for your detailed reply. It helps a lot.
