### ISSUE TITLE
What's the difference between capacitive touchscreen resolution and its touch location recognition precision?

### ISSUE THREAD

**Issue by QueueRear** [FIGLAB/3DHandPose#2]
Dear Prof. @sven-mayer,

I'm sorry for bothering you again, but there's another confusion hitting my mind. 

The touch location recognition precision of capacitive screens can reach to display pixel level. For instance, when drawing pictures or signing names on a tablet, we will find the path that our fingers or pencils have gone through can be precisely reflected on the screen with a high resolution. Therefore, I used to think the resolution of touchscreens is close to that of the monitor, but it is mentioned in your paper that the capacitive touchscreen sensor resolution is around 4 mm. I am curious about how this figure is calculated, and also puzzled how a touchscreen can obtain such a high recognition accuracy with a low capacitive screen sensor resolution.

Best wishes,
QueueRear

**Comment by sven-mayer** [comment]
The question is not related to the project -- close.
